#!/bin/bash

#####ISO-BUILD#####
sudo rm -rf /home/$USER/git/anarchy-iso/work/

echo "##################################"
echo "           BUILDING ISO           "
echo "##################################"

sudo mkarchiso -v .

echo "##################################"
echo "             ISO BUILT            "
echo "##################################"

