exec-once = awww-daemon
exec-once = swaync
exec-once = /usr/local/bin/awww.sh
exec-once = /usr/local/bin/tokyo-night.sh
exec-once = /usr/local/bin/font.sh
exec-once = wal --theme ~/.config/pywal/themes/active.json
exec-once = sleep 2 && hyprctl reload
